package com.vineet.posts.infrastructure.adapter.persistence;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA Entity for Post persistence.
 * 
 * =============================================================================
 * WHY A SEPARATE JPA ENTITY?
 * =============================================================================
 * 
 * We have TWO classes representing a "Post":
 * 
 *   1. Post.java (Domain layer)
 *      - Pure Java, no annotations
 *      - Business logic and rules
 *      - Framework-agnostic
 * 
 *   2. PostJpaEntity.java (Infrastructure layer) ← THIS FILE
 *      - JPA annotations (@Entity, @Column, etc.)
 *      - Maps to database table
 *      - Framework-specific (JPA/Hibernate)
 * 
 * WHY NOT JUST ADD JPA ANNOTATIONS TO DOMAIN Post?
 * 
 *   If we did:
 *   - Domain would depend on JPA (jakarta.persistence.*)
 *   - Can't test domain without JPA libraries
 *   - Domain is "polluted" with infrastructure concerns
 *   - Harder to switch databases (annotations are JPA-specific)
 * 
 *   With separate classes:
 *   - Domain stays pure Java
 *   - Infrastructure handles all database details
 *   - Clear separation of concerns
 * 
 * =============================================================================
 * JPA ANNOTATIONS EXPLAINED
 * =============================================================================
 * 
 * @Entity    - "This class maps to a database table"
 * @Table     - "The table is named 'posts'" (optional, defaults to class name)
 * @Id        - "This field is the primary key"
 * @Column    - "This field maps to this column" (with options)
 */
@Entity
@Table(name = "posts")
public class PostJpaEntity {
    
    /**
     * Primary key using UUID.
     * 
     * @Id - Marks this as the primary key
     * 
     * @Column options:
     *   - columnDefinition = "uuid" → Use PostgreSQL's native UUID type
     *   - updatable = false → ID never changes after insert
     *   - nullable = false → ID is required (NOT NULL constraint)
     * 
     * We DON'T use @GeneratedValue because:
     *   - We generate UUID in domain layer (Post.create())
     *   - Not auto-generated by database
     */
    @Id
    @Column(name = "id", columnDefinition = "uuid", updatable = false, nullable = false)
    private UUID id;
    
    /**
     * Post title.
     * 
     * @Column options:
     *   - name = "title" → Column name (optional if same as field)
     *   - nullable = false → Creates NOT NULL constraint
     *   - length = 255 → VARCHAR(255) - max length
     */
    @Column(name = "title", nullable = false, length = 255)
    private String title;
    
    /**
     * Post content.
     * 
     * @Column options:
     *   - columnDefinition = "TEXT" → Use TEXT type instead of VARCHAR
     *   - TEXT has no length limit (good for long content)
     */
    @Column(name = "content", columnDefinition = "TEXT")
    private String content;
    
    /**
     * When the post was created.
     * 
     * @Column options:
     *   - updatable = false → This column never changes after insert
     *   - nullable = false → Required field
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    /**
     * When the post was last updated.
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
    
    // =========================================================================
    // CONSTRUCTORS
    // =========================================================================
    
    /**
     * No-arg constructor required by JPA.
     * 
     * JPA/Hibernate creates objects using reflection:
     *   1. Create empty object: new PostJpaEntity()
     *   2. Set fields via reflection: entity.id = value
     * 
     * Protected = only JPA can use it (not public API)
     */
    protected PostJpaEntity() {
    }
    
    /**
     * All-args constructor for creating from domain entity.
     * 
     * Used in JpaPostRepository when converting Post → PostJpaEntity
     */
    public PostJpaEntity(UUID id, String title, String content,
                         LocalDateTime createdAt, LocalDateTime updatedAt) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    
    // =========================================================================
    // GETTERS
    // =========================================================================
    
    public UUID getId() {
        return id;
    }
    
    public String getTitle() {
        return title;
    }
    
    public String getContent() {
        return content;
    }
    
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
    
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }
    
    // =========================================================================
    // SETTERS (needed by JPA for updates)
    // =========================================================================
    
    /**
     * Setters for fields that can change.
     * 
     * Note: No setter for id (never changes) or createdAt (never changes)
     */
    public void setTitle(String title) {
        this.title = title;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
