package com.vineet.posts.infrastructure.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * OpenAPI/Swagger configuration.
 * 
 * This customizes the API documentation generated by SpringDoc.
 * 
 * Access the documentation at:
 *   - Swagger UI: http://localhost:8080/swagger-ui.html
 *   - OpenAPI JSON: http://localhost:8080/api-docs
 * 
 * =============================================================================
 * WHAT IS OPENAPI/SWAGGER?
 * =============================================================================
 * 
 * OpenAPI (formerly Swagger) is a specification for describing REST APIs.
 * 
 * Benefits:
 *   - Interactive documentation (try APIs in browser)
 *   - Auto-generated from your code
 *   - Can generate client SDKs
 *   - Industry standard
 * 
 * SpringDoc automatically scans your @RestController classes and generates
 * documentation. This config customizes the general API info.
 */
@Configuration
public class OpenApiConfig {
    
    @Bean
    public OpenAPI customOpenAPI() {
        return new OpenAPI()
                .info(new Info()
                        .title("Posts API")
                        .version("1.0.0")
                        .description("""
                                REST API for managing blog posts.
                                
                                This API provides CRUD operations for posts:
                                - Create new posts
                                - Retrieve posts (single or all)
                                - Update existing posts
                                - Delete posts
                                
                                Built with Spring Boot 3.x and Hexagonal Architecture.
                                """)
                        .contact(new Contact()
                                .name("Vineet")
                                .email("vineet@example.com")
                                .url("https://github.com/vineet-s1nghal"))
                        .license(new License()
                                .name("MIT License")
                                .url("https://opensource.org/licenses/MIT"))
                );
    }
}
